### ISSUE TITLE
New tab for Unit tags

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#807]
**Background**
The so-called “Read Tab” really involves two distinct functions:
- a list of Units is displayed in the left Nav pane 
- editing functions are turned off
But it is better to separate these 2 functions, because  each is independently useful. This will make it easier for the user to attach Tags to Units. (This should be combined with the new tab design, which facilitates assigning unit tags.)

**What to do**
1. The “Read” tab becomes the “Unit” tab. (Simply rename it.)
2.  The “Read” button now stands for “Read mode”. The user can combine Read mode with any tab (Units, Track, Stack, etc.), to avoid accidental editing. 
3. When the user wants to edit, they click the “Read” toggle to turn edting on. (A more standard icon for this would be a pen icon, to indicate editing.)
4. By default, Rezonator starts with the “Unit” tab selected, and “Read” mode turned on (that is, editing is turned off).
5. Making a wide tab makes it easy to include unit-level fields, which can be edited to assign tags to units.

**Screenshot**
To implement the new Unit tab, follow the design for the new tab, as shown here: 
- [Unit tab ](![Tabs - units](https://user-images.githubusercontent.com/22628444/108733081-d3618700-7536-11eb-8653-eaa3558d3f5a.PNG))
 
**Alternatives you have considered**
This solution takes the place of a middle pane (3rd pane) for the Nav window, which is no longer needed.     

**Related to**
#808 : [New tab and pane design](https://docs.google.com/document/d/16YOYPdDBw-jXuOayTeedBXIIm7WBtWQoiRjlbv32ukw/edit?usp=sharing) (Google Docs)

**Tasks**
- [ ] Example Task - 1 hr
- [ ] Example Task- 2 hr
- [ ] Example Task- 3 hr
- [ ] Example Task - 4 hr

**Additional points**
The new tab design should allow the following actions for each Nav window pane:
1. In the upper right corner of each Nav window pane contains several buttons:
- 3 small buttons on the right allowing the user to close, minimize, or maximize each Nav pane individually.
- a 3-dot icon provides a drop-down menu, allowing further actions that appy to the Nav pane.
- the 2 groups of buttons are separated by a separator icon (a vertical pipe)
2. By providing a large horizontal bar for the selected tab, this design makes plenty of space for buttons (icons for actions), eliminating the need to put icons on each individual tab.
3, Available actions are show with icons for show/hide (eyeball), pick/unpick (funnel), align/unalign (icons are shown on the tab bar)
4.  A "select all" checkbox is shown in the header, next to the "Seq" or "Name" header label. This button selects all checkboxes below it (or unselects them all).
5. Individual checkboxes appear to the left of each listed item. With these checkboxes, the user can:
- select several items from the list
- apply the same function to each of the selected items
6. All checkboxes appear only when the user hovers over the item, or when checked (as in Windows Explorer).
7. One of the menus should provide options to:
- display more or fewer tabs
- choose which tabs to display
8. Because there is so much use of color in Rezonator, to make the selected tab stand out:
- the selected tab should be shown in white (in the standard theme)
- Even in dark theme, the selected tab should be shown in white

**Resources**
For an interesting (and technical) discussion of UI design, addressing many issues including tabs and touch, see the following:   

[Google Chrome redesign](https://medium.com/google-design/redesigning-chrome-desktop-769aeb5ab987) (blog): Tabs, touch, etc)
