### ISSUE TITLE
Move Rezonator code to new "Rezonators" organization account on GitHub 

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#993]
Move the Rezonator codebase to the new "Rezonators" ORGANIZATION repo on GitHub.
See: https://github.com/rezonators

**Steps**
- [ ] Remove large files from Git history (because they block the transfer to new org repo). #1524 
- [ ] Remove CSV files from Git history #603 
- [ ] Move **Rezonator** code to **[Rezonators\Rezonator](https://github.com/rezonators/rezonator)**
- [ ] Move **Guide** code to **[Rezonators\Rezonator](https://github.com/rezonators/rezonator)** #1325

**Comment by kayaulai** [comment]
https://github.com/rezonator
